{% set version = "0.1.1" %}

package:
  name: django-makemessages-xgettext
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-makemessages-xgettext/django-makemessages-xgettext-{{ version }}.tar.gz
  sha256: 5d0500c7aad704759911cb1b98b6f223f0702e13e504459b4dbda81665aa174f

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django >=1.7

test:
  commands:
    - python -c "import django; from django.conf import settings; settings.configure(INSTALLED_APPS=['django_makemessages_xgettext']); django.setup(); import django_makemessages_xgettext;"

about:
  home: https://github.com/resulto/django-makemessages-xgettext
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'makemessages command that allows for arguments to be passed to xgettext.'

  description: |
    Allow makemessages to receive additional parameters to pass to xgettext.
  doc_url: https://github.com/resulto/django-makemessages-xgettext
  dev_url: https://github.com/resulto/django-makemessages-xgettext

extra:
  recipe-maintainers:
    - xmnlab
