travis:
  secure:
    BINSTAR_TOKEN: 1yphH7/M0sm4GXJTlnC7HoGKO4pmVN6Dp8eSwSZ3OJfRY2c+xE3esT/+aRug0MJnpUcXhyiHXavfec53PCLu8qUE7UPhuhtcvX4VI9pw2IS8AGi9ZXNnbX/+rNSy0KekAMrduWG+vzwP1NPDYzGc5ypk0X9LprFWykqzTSQpqQcF1u8eDYvHR71cIFZuvr+vxVLfoVgwqYxa12O7on//23xx+ztVrv6QmiGYsg6qgW/ilHFmIrih2CgnGp64rHdO48q7nW+Qxf0AVIwqy9/DhT9pzKftDFlDOfQFTOOnxKjM2exwc0Y1LOb7rKrODFH8YwigiH7NFWNv1SYWrYGhe8DuDX0+5/axhzpTpW8zq1Kl5Adj9z1cz252qqtM/Ptx/F+wRWw9NE4QFaIbNWJaB2n+Wp9iprxESlwbSAnB95zN+Nh+chZbyQQhGa5Uo4c46v+eGlqZkRw3FeUJyKb0/mw4wrs+4kgXIJhxRTD33EkNb9BCjnp75I9PQ+wwBMGckeyPgWd9AwePlXxY7S8MIVU2RLBCaYmLkEC+bNE1HlnpUEr5HeCy9YMEyjb1gsr9JwHtDFsrc9eK0Rol9gzmfa6MOMF98cJoGN1SYzsdyurdkP+zGgveGTyO3FZP+RFwg2fXRkQLV003RPu8yS2z66jNLwaAGOuZkUE7tm+azAo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
